[package]
name = "ash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = { version = "*", features = ["linked"] }
ash-window = "*"
winit = "*"
raw-window-handle = "0.5.0"
num = "0.4.0"
